### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by spoenemann** [apust/vscode-rubber-theme#1]
This project doesn't have any license. Please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT.

A license is mandatory for publishing your extension to [Open VSX](https://open-vsx.org/). Its publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without license. See the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more details.

**Comment by apust** [comment]
Added in https://github.com/apust/vscode-rubber-theme/commit/08e6e5855a47673cfc3b648e700f3c9db39b7df5

**Comment by spoenemann** [comment]
Great! Could you also add an entry `"license": "MIT"` to the package.json? That helps when the extension metadata is processed automatically.

**Comment by apust** [comment]
Done (https://github.com/apust/vscode-rubber-theme/commit/15449acb4712ed67c7da75d7857d1da7097fbc9c).

**Comment by spoenemann** [comment]
Thank you! An older version of your extension has been published to Open VSX by someone else:
https://open-vsx.org/extension/apust/rubber-theme/0.1.0

Would you like to take over publishing yourself? Instructions are here:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
